### ISSUE TITLE
A Brief History of my Task Managemen

### ISSUE THREAD

**Issue by Anonymous290** [cf020031308/cf020031308.github.io#53]
Hello, I'm sorry for using this platform to ask this question, I don't want to bother your work.

I am reading your website about [this article](https://cf020031308.github.io/blog/a-brief-history-of-my-task-management/), very useful!
Can you tell me which mobile application you are using for this -> https://cf020031308.github.io/blog/a-brief-history-of-my-task-management/WechatIMG590.jpeg

**Comment by cf020031308** [comment]
@Anonymous290 That is fine. You are welcome to comment my blog here because Issues of this repo are just meant to be for this purpose.
The application is Nutstore Markdown Editor, used for editing markdown files stored remotely in [Nutstore](https://www.jianguoyun.com). And Nutstore is a netdisk (like dropbox) popular in China.

**Comment by 720905** [comment]
Oh wow. Thank you very much, this app look convinient!
